#!/usr/bin/env python

from unicode_helpers import most_common_unicode_block
import click

@click.command()
@click.argument("input_file", type=click.File("r"), default="-")
@click.argument("output_file", type=click.File("w"), default="-")
def main(input_file, output_file):
    with input_file, output_file:
        for line in input_file:
            script = most_common_unicode_block(line)
            output_file.write(f"{script}\n")

if __name__ == "__main__":
    main()
