#!/usr/bin/env bash

# Get anecdata for language. Run this in the dump folder. (e.g. by symlinking)

readonly anecdata_folder=moveme_script_standardization_anecdata
lang=$1

[ $# -lt 1 ] && echo "Please provide a language!" && exit 1

lang_data=$(xsv search -d'\t' -s language "^${lang}\$" combined/combined_postprocessed.tsv \
    | xsv sort -s alias,type \
    | xsv fmt -t'\t')

# in case we don't get enough rows, exit instead of piping to vim
n_lines=$(echo "$lang_data" | wc -l | cut -d' ' -f1)

[ $n_lines -lt 2 ] && echo "No data found for $lang! Exiting..." && exit 1

echo "$lang_data" | vipe > $anecdata_folder/anecdata_${lang}.tsv
